### ISSUE TITLE
I broke the build...

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-provider-verifier-npm#3]
Not sure how... I only bumped the version number of the standalone package...

https://travis-ci.org/pact-foundation/pact-provider-verifier-npm/builds/261229517#L4099

Got any idea @mefellows ?

**Comment by mefellows** [comment]
Not sure, but i'll take a look! It looks like it ran on new servers (Trusty), shouldn't be the cause though. I did notice this locally a while back but thought maybe it was my machine.

I'm currently investigating if there is an option to _not_ have to have all of these modules in separate places. There might be away to do the install directly when we install pact-node (or even just pact itself).

Having all of these modules seems a bit... messy.

**Comment by bethesque** [comment]
It does. I'm afraid I'm not enough of a node person to think of a better way to do it.

**Comment by mefellows** [comment]
In any case, i've fixed this (see the `.travis.yml` file). 

I'm not sure why, but it was performing an npm link on all os/architectures which I can't see how it would work. Linking only the correct architecture seems to have done the trick.
